name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Vérification index.html
        run: |
          if [ -f "./src/frontend/index.html" ]; then
            echo "Le fichier index.html existe"
          else
            echo "Erreur : index.html n'existe pas!"
            exit 1
          fi

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_GLACIER_035228203 }}
          action: "upload"
          app_location: "./src/frontend"
          api_location: ""
          output_location: "./src/frontend"
          github_id_token: ${{ steps.idtoken.outputs.result }}

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@12.6.1
        with:
          urls: |
            https://to-do.filipmihajovic.emf-informatique.ch/
          configPath: ./.lighthouserc.json
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
