name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "acrinfofd22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "todo-backend-filip" # Nom de votre image
  VERSION: "1.1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: etape à réaliser
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REG_NAME }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          docker build -t ${{env.REG_NAME}}/${{env.IMAGE_NAME}} ./src/backend
          docker push ${{env.REG_NAME}}/${{env.IMAGE_NAME}}:${{env.VERSION}}
